#!/usr/bin/env python3
"""Regenerate triage.md from data/triage.tsv (+ data/inventory.tsv for provenance).

triage.md is a projection, like the CSV and the audit: edit triage.tsv, then run this.
Every repo appears exactly once, with its reason, so nothing is discarded silently.
"""
import csv
import os
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TRIAGE = os.path.join(HERE, "triage.tsv")
INV = os.path.join(HERE, "inventory.tsv")
OUT = os.path.join(ROOT, "triage.md")

ORDER = ["IN", "OUT", "DEFERRED", "REVIEW"]
MEANING = {
    "IN": "design files present (or ruled in by the user); expands to CSV rows",
    "OUT": "no design files in the tree, or ruled out by the user",
    "DEFERRED": "set aside by the user for a later pass",
    "REVIEW": "needs a ruling",
}


def read_tsv(path):
    with open(path, newline="") as f:
        return list(csv.DictReader(f, delimiter="\t"))


def cell(s):
    s = (s or "").strip()
    if s == "NONE":
        s = ""
    return s.replace("|", "\\|")


def main():
    rows = read_tsv(TRIAGE)
    inv = {r["repo"]: r for r in read_tsv(INV)}

    missing = [r["repo"] for r in rows if r["repo"] not in inv]
    dupes = [k for k, n in Counter(r["repo"] for r in rows).items() if n > 1]
    bad = [r["repo"] for r in rows if r["bucket"] not in ORDER]
    unlisted = sorted(set(inv) - {r["repo"] for r in rows})
    if missing or dupes or bad or unlisted:
        sys.exit(f"triage.tsv inconsistent: not in inventory={missing} dupes={dupes} "
                 f"bad bucket={bad} inventory repos without triage={unlisted}")

    counts = Counter(r["bucket"] for r in rows)
    starred = sum(1 for r in rows if inv[r["repo"]]["page"] != "user-added")
    added = len(rows) - starred
    dirs = sum(int(r["module_dirs"] or 0) for r in rows if r["bucket"] == "IN")

    L = []
    L.append(f"# Triage — {len(rows)} repos\n")
    L.append("Generated by `data/triage_md.py` from `data/triage.tsv`. Do not edit by hand.\n")
    L.append(f"{starred} repos from the star list + {added} added at the user's request "
             "(`page = user-added` in `data/inventory.tsv`). Nothing is discarded: every repo "
             "appears below with its reason. Reasons starting `user:` are the user's rulings.\n")
    L.append("**The exclusion test is the absence of hardware design files, never the presence "
             "of firmware.** A description can put a repo *in*, but never on its own take one "
             "*out* — every exclusion was checked against the repo's actual file tree.\n")
    L.append("| bucket | count | meaning |\n|---|---|---|")
    for b in ORDER:
        if counts[b]:
            L.append(f"| {b} | {counts[b]} | {MEANING[b]} |")
    L.append("")
    L.append(f"Module directories detected in IN repos: **{dirs}**. This is a mechanical upper "
             "bound, not a row count — revisions, per-board folders, legacy content and panels "
             "are not yet collapsed, and zipped or document-only repos count 0 until expanded.\n")

    for b in ["OUT", "DEFERRED", "REVIEW"]:
        sel = [r for r in rows if r["bucket"] == b]
        if not sel:
            continue
        L.append(f"## {b}\n")
        L.append("| repo | reason | description |\n|---|---|---|")
        for r in sel:
            L.append(f"| `{r['repo']}` | {cell(r['reason'])} | {cell(r['description'])} |")
        L.append("")

    sel = sorted((r for r in rows if r["bucket"] == "IN"),
                 key=lambda r: (-int(r["module_dirs"] or 0), r["repo"].lower()))
    L.append("## IN\n")
    L.append("Sorted by detected module directories. `eda` is what the tree scan recognised.\n")
    L.append("| repo | dirs | eda | reason | description |\n|---|---|---|---|---|")
    for r in sel:
        L.append(f"| `{r['repo']}` | {r['module_dirs'] or 0} | {cell(r['eda_kinds'])} | "
                 f"{cell(r['reason'])} | {cell(r['description'])} |")
    L.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(L))
    print(f"wrote {OUT}: " + ", ".join(f"{b} {counts[b]}" for b in ORDER if counts[b]))


if __name__ == "__main__":
    main()
